spring.application.name=fccabApp
# Server Port
server.port=4556

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5444/floxgeodb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
