# spring.application.name=uberApp

# #DB configuration
# spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?useSSL=false
# spring.datasource.username=
# spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data.sql

# #security config
# jwt.secretKey = paiosdfqg43j51b4hjbhcafifa87dsf6hk32jhkrj9a7dfhkjhalkasdf97823


spring.application.name=fccabApp

server.port=4556

spring.datasource.url=jdbc:postgresql://localhost:5444/floxgeodb
spring.datasource.username=postgres
spring.datasource.password=NewPassword123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secretKey=abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your@gmail.com
spring.mail.password=xxxxxxxxxxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true